[package]
name = "gorse"
version = "0.1.0"
edition = "2021"
description = "Rust SDK for gorse recommender system"
readme = "README.md"
homepage = "https://gorse.io"
repository = "https://github.com/gorse-io/gorse-rs"
license = "Apache-2.0"
keywords = ["gorse", "machine-learning", "collaborative-filtering", "recommender-system"]
categories = ["algorithms", "science"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
